rule alignReads:
    input:
        "../data/genome.fa",
        "../data/samples/{sample}.fastq"
    output:
        "mapped_reads/{sample}.bam"
    shell:
        "touch {output}"

rule samtools_sort:
    input:
        "mapped_reads/{sample}.bam"
    output:
        "sorted_reads/{sample}.bam"
    shell:
        "touch {output}"

rule samtools_index:
    input:
        "sorted_reads/{sample}.bam"
    output:
        "sorted_reads/{sample}.bam.bai"
    shell:
        "touch {output}"
